DOMS/urls.py
from django.conf.urls import url
from django.contrib import admin
from orders import views as my_order
from django.contrib.auth import views as auth
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^order/uploadline/$',my_order.upload_line,name='uploadline'),
    url(r'^order/upload/$',my_order.upload,name='upload'),
    url(r'^order/uploadbilladdress/$',my_order.upload_bill_address,name='uploadbilladdress'),
    url(r'^order/uploadshipaddress/$',my_order.upload_ship_address,name='uploadshipaddress'),
    url(r'^purchase/uploadaccount/$',my_order.upload_account,name='uploadaccount'),
    url(r'^purchase/uploadpart/$',my_order.upload_part,name='uploadpart'),
    url(r'^purchase/uploadpurchase/$',my_order.upload_purchase,name='uploadpurchase'),
    url(r'^order/uploadsalesreport/$',my_order.upload_sales_report,name='uploadsalesreport'),
    url(r'^order/uploadpurchasereport/$',my_order.upload_purchase_report,name='uploadpurchasereport'),
    url(r'^order/uploadrevenue/$',my_order.upload_revenue,name='uploadrevenue'),

    url(r'^order/salesbootstrap/$',my_order.BootstrapFilterView, name='bootstrap'),
    url(r'^order/sales3bootstrap/$',my_order.BootstrapFilterView_sales3, name='sales3bootstrap'),
    url(r'^order/purchase2bootstrap/$',my_order.BootstrapFilterView_purchase2, name='purchase2bootstrap'),
    url(r'^order/purchase3bootstrap/$',my_order.BootstrapFilterView_purchase3, name='purchase3bootstrap'),
    url(r'^order/foundry1bootstrap/$',my_order.BootstrapFilterView_foundry1, name='foundry1bootstrap'),
    url(r'^order/foundry2bootstrap/$',my_order.BootstrapFilterView_foundry2, name='foundry2bootstrap'),
    url(r'^order/foundry3bootstrap/$',my_order.BootstrapFilterView_foundry3, name='foundry3bootstrap'),
    url(r'^order/extrusion2bootstrap/$',my_order.BootstrapFilterView_extrusion2, name='extrusion2bootstrap'),
    url(r'^order/extrusion3bootstrap/$',my_order.BootstrapFilterView_extrusion3, name='extrusion3bootstrap'),
    url(r'^order/fabrication2bootstrap/$',my_order.BootstrapFilterView_fabrication2, name='fabrication2bootstrap'),
    url(r'^order/fabrication3bootstrap/$',my_order.BootstrapFilterView_fabrication3, name='fabrication3bootstrap'),
    url(r'^order/anodizing2bootstrap/$',my_order.BootstrapFilterView_anodizing2, name='anodizing2bootstrap'),
    url(r'^order/anodizing3bootstrap/$',my_order.BootstrapFilterView_anodizing3, name='anodizing3bootstrap'),
    url(r'^order/shipping2bootstrap/$',my_order.BootstrapFilterView_shipping2, name='shipping2bootstrap'),
    url(r'^order/shipping3bootstrap/$',my_order.BootstrapFilterView_shipping3, name='shipping3bootstrap'),

    url(r'^order/saleschart/$', my_order.sales_chart, name='saleschart'),
    url(r'^order/indexsalesreport/$', my_order.index_sales_report, name='indexsalesreport'),
    url(r'^order/deletesalesreport/$', my_order.destroy_sales_report, name='destroysalesreport'),

    url(r'^order/purchasechart/$', my_order.purchase_chart, name='purchasechart'),
    url(r'^order/indexpurchasereport/$', my_order.index_purchase_report, name='indexpurchasereport'),
    url(r'^order/deletepurchasereport/$', my_order.destroy_purchase_report, name='destroypurchasereport'),
    
    url(r'^admin/', admin.site.urls),
    url(r'^$', my_order.index_chart, name='index'),
    url(r'^orders$', my_order.index, name='home'),
    url(r'^order/(?P<order_id>\d+)/$', my_order.show, name='show'),

    url(r'^order/price/(?P<price_id>\d+)/$', my_order.showPrice, name='showprice'),
    url(r'^order/new/price/$', my_order.new_price, name='newprice'),
    url(r'^order/indexprice/$', my_order.indexprice, name='indexprice'),
    url(r'^order/editprice/(?P<price_id>\d+)/$', my_order.editPrice, name='editprice'),
    url(r'^order/deleteprice/(?P<price_id>\d+)/$', my_order.destroyPrice, name='deleteprice'),
    
    url(r'^order/line/(?P<line_id>\d+)/$', my_order.showLine, name='showline'),
    url(r'^order/indexline/$', my_order.indexline, name='indexline'),
    url(r'^order/newline/$', my_order.newLine, name='newline'),
    url(r'^order/editline/(?P<line_id>\d+)/$', my_order.editLine, name='editline'),
    url(r'^order/deleteline/(?P<line_id>\d+)/$', my_order.destroyLine, name='deleteline'),


    url(r'^order/newcustomername/$', my_order.new_customer_name, name='newcustomername'),
    url(r'^order/indexcustomername/$', my_order.index_customer_name, name='indexcustomername'),
    url(r'^order/indexcustomername/delete/(?P<customer_id>\d+)/$', my_order.destroy_customer_name, name='destroy_customer_name'),

    url(r'^order/newbilladdress/$', my_order.new_bill_address, name='newbilladdress'),
    url(r'^order/newshipaddress/$', my_order.new_ship_address, name='newshipaddress'),
    url(r'^order/indexbilladdress/$', my_order.index_bill_address, name='indexbilladdress'),
    url(r'^order/indexshipaddress/$', my_order.index_ship_address, name='indexshipaddress'),
    url(r'^order/indexbilladdress/delete/(?P<billAddress_id>\d+)/$', my_order.destroy_bill_address, name='destroy_bill_address'),
    url(r'^order/indexshipaddress/delete/(?P<shipAddress_id>\d+)/$', my_order.destroy_ship_address, name='destroy_ship_address'),

    url(r'^purchase/newpart/$', my_order.new_part, name='newpart'),
    url(r'^purchase/newaccount/$', my_order.new_account, name='newaccount'),
    url(r'^purchase/indexpart/$', my_order.index_part, name='indexpart'),
    url(r'^purchase/indexaccount/$', my_order.index_account, name='indexaccount'),
    url(r'^purchase/indexpart/delete/(?P<part_id>\d+)/$', my_order.destroy_part, name='destroy_part'),
    url(r'^purchase/indexaccount/delete/(?P<account_id>\d+)/$', my_order.destroy_account, name='destroy_account'),

    url(r'^purchase/new/$', my_order.newPurchase, name='newpurchase'),
    url(r'^purchase$', my_order.indexPurchase, name='indexpurchase'),
    url(r'^purchase/edit/(?P<purchase_id>\d+)/$', my_order.editPurchase, name='editpurchase'),
    url(r'^purchase/delete/(?P<purchase_id>\d+)/$', my_order.destroyPurchase, name='deletepurchase'),
    url(r'^purchase/(?P<purchase_id>\d+)/$', my_order.showPurchase, name='showpurchase'),
    
    url(r'^order/new/$', my_order.new, name='new'),
    url(r'^order/edit/(?P<order_id>\d+)/$', my_order.edit, name='edit'),
    url(r'^order/delete/(?P<order_id>\d+)/$', my_order.destroy, name='delete'),
    url(r'^users/login/$', auth.login, {'template_name': 'login.html'}, name='login'),
    url(r'^users/logout/$', auth.logout, {'next_page': '/'}, name='logout'),
    url(r'^users/change_password/$', login_required(auth.password_change), {'post_change_redirect' : '/','template_name': 'change_password.html'}, name='change_password'),

    url(r'^order/billet/(?P<billet_id>\d+)/$', my_order.showBillet, name='showbillet'),
    url(r'^order/newbillet/$', my_order.new_billet, name='newbillet'),
    url(r'^order/indexbillet/$', my_order.index_billet, name='indexbillet'),
    url(r'^order/editbillet/(?P<billet_id>\d+)/$', my_order.editBillet, name='editbillet'),
    url(r'^order/deletebillet/(?P<billet_id>\d+)/$', my_order.destroyBillet, name='deletebillet'),
    
    url(r'^order/log/(?P<log_id>\d+)/$', my_order.showLog, name='showlog'),
    url(r'^order/newlog/$', my_order.new_log, name='newlog'),
    url(r'^order/indexlog/$', my_order.index_log, name='indexlog'),
    url(r'^order/editlog/(?P<log_id>\d+)/$', my_order.editLog, name='editlog'),
    url(r'^order/deletelog/(?P<log_id>\d+)/$', my_order.destroyLog, name='deletelog'),

    url(r'^order/departmentnavigation/$', my_order.department_navigation, name='departmentnavigation'),
    url(r'^order/departmenttrendnavigation/$', my_order.department_trend_navigation, name='departmenttrendnavigation'),

    url(r'^order/foundrychart/$', my_order.foundry_chart, name='foundrychart'),
    url(r'^order/extrusionchart/$', my_order.extrusion_chart, name='extrusionchart'),
    url(r'^order/fabricationchart/$', my_order.fabrication_chart, name='fabricationchart'),
    url(r'^order/anodizingchart/$', my_order.anodizing_chart, name='anodizingchart'),
    url(r'^order/shippingchart/$', my_order.shipping_chart, name='shippingchart'),
    url(r'^order/paintchart/$', my_order.paint_chart, name='paintchart'),

    url(r'^order/revenuechart/$', my_order.revenue_chart, name='revenuechart'),
    url(r'^order/revenue/(?P<revenue_id>\d+)/$', my_order.showRevenue, name='showrevenue'),
    url(r'^order/newrevenue/$', my_order.new_revenue, name='newrevenue'),
    url(r'^order/indexrevenue/$', my_order.index_revenue, name='indexrevenue'),
    url(r'^order/editrevenue/(?P<revenue_id>\d+)/$', my_order.editRevenue, name='editrevenue'),
    url(r'^order/deleterevenue/(?P<revenue_id>\d+)/$', my_order.destroyRevenue, name='deleterevenue'),

    url(r'^order/checksales/(?P<sales_id>\d+)/$', my_order.check_sales, name='checksales'),
    url(r'^order/checkpurchase/(?P<purchase_id>\d+)/$', my_order.check_purchase, name='checkpurchase'),
    url(r'^order/checkgeneral/(?P<general_id>\d+)/$', my_order.check_general, name='checkgeneral'),

    url(r'^order/newfoundry/$', my_order.new_foundry, name='newfoundry'),
    url(r'^order/indexfoundry/$', my_order.index_foundry, name='indexfoundry'),
    url(r'^order/editfoundry/(?P<foundry_id>\d+)/$', my_order.editFoundry, name='editfoundry'),
    url(r'^order/deletefoundry/(?P<foundry_id>\d+)/$', my_order.destroyFoundry, name='deletefoundry'),

    #url(r'^order/newextrusion/$', my_order.new_extrusion, name='newextrusion'),
    #url(r'^order/indexextrusion/$', my_order.index_extrusion, name='indexextrusion'),
    #url(r'^order/editextrusion/(?P<extrusion_id>\d+)/$', my_order.editExtrusion, name='editextrusion'),
    #url(r'^order/deleteextrusion/(?P<extrusion_id>\d+)/$', my_order.destroyExtrusion, name='deleteextrusion'),
    url(r'^order/todolistextrusion/$', my_order.todolistextrusion, name='todolistextrusion'),
    url(r'^order/todo_completed/(?P<order_id>\d+)/$', my_order.todo_completed, name='todo_completed'),

orders/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from . import formsAddress
from django.utils.timezone import datetime


class OrderForm(ModelForm):
    
    OPTIONS = (
        ('',''),
        ('Yes','Y'),
        ('No','N'),
    )
    
    OPTIONS2 = (
        ('Confirm', 'Confirm'),
        ('Extrusion', 'Extrusion'),
        ('Fabrication', 'Fabrication'),
        ('Anodizing', 'Anodizing'),
        ('Shipping', 'Shipping'),
        ('Cancelled', 'Cancelled')
    )
    OPTIONS3 = (
        ('',''),
        ('O','O'),
        ('S','S'),
    )
    OPTIONS4 = (
        ('',''),
        ('A','A'),
        ('R','R'),
    )
    OPTIONS5 = (
        ('',''),
        ('RE','RE'),
        ('CM','CM'),
    )
    OPTIONS6 = (
        ('',''),
        ('02','02'),
        ('03','03'),
        ('04','04'),
        ('05','05'),
        ('06','06'),
    )

    OPTIONS7 = (
        ('Pending Payment', 'Pending Payment'),
        ('Payment Received', 'Payment Received'),
    )

    OPTIONS8 = (('',''),('Shipped','Shipped'),('Not Shipped','Not Shipped'),('Shipping Finished','Shipping finished'),)

 

    order_status = forms.TypedChoiceField(required=False, choices=OPTIONS2, widget=forms.RadioSelect)
    order_received = forms.ChoiceField(choices=OPTIONS)
    price_method = forms.ChoiceField(choices=OPTIONS3)
    surcharge = forms.ChoiceField(choices=OPTIONS)
    A_R_credit = forms.ChoiceField(choices=OPTIONS4)
    fax_ASN = forms.ChoiceField(choices=OPTIONS)
    email_ASN = forms.ChoiceField(choices=OPTIONS)
    order_type = forms.ChoiceField(choices=OPTIONS5)
    customer_id = forms.ModelChoiceField(queryset=CustomerName.objects.filter(active='1'), empty_label='')
    billAddress_id = forms.ModelChoiceField(queryset=BillAddress.objects.filter(active='1'), empty_label='')
    shipAddress_id = forms.ModelChoiceField(queryset=ShipAddress.objects.filter(active='1'), empty_label='')
    #line_id = forms.ModelChoiceField(queryset=Line.objects.filter(active='1'), empty_label='')
    payment_status =forms.TypedChoiceField(initial="Pending Payment",required=False, choices=OPTIONS7, widget=forms.RadioSelect)
    shipping_status = forms.ChoiceField(choices=OPTIONS8,required=False)
    extrusion_completed = forms.TypedChoiceField(required=False, choices=OPTIONS, widget=forms.RadioSelect)
    shipping_completed = forms.TypedChoiceField(required=False, choices=OPTIONS, widget=forms.RadioSelect)
    fabrication_completed = forms.TypedChoiceField(required=False, choices=OPTIONS, widget=forms.RadioSelect)
    anodizing_completed = forms.TypedChoiceField(required=False, choices=OPTIONS, widget=forms.RadioSelect)
    
    
    class Meta:
        model = Order
        fields = ['line','workorder_number','total_quantity','backorder_quantity','shipping_quantity','total_weight','backorder_weight',
                  'die_number','part_number','required_date','freight','quote','contract','order_status','order_value',
                  'order_received', 'price_method', 'surcharge', 'A_R_credit', 'fax_ASN', 'email_ASN', 'order_type',
                  'order_number', 'order_type', 'ordered_date', 'price_details', 'kit_details', 'ship_via', 'attention',
                  'ship_instructions', 'F_O_B', 'warehouse', 'sales_rep', 'product_line', 'COS_project', 'sales_account',
                  'order_value', 'staus_number', 'contact_name', 'phone_number', 'ship_cond', 'credit_control', 'ASN_contact',
                  'ASN_title', 'ASN_fax_num', 'email_addr', 'customer_id', 'billAddress_id', 'shipAddress_id','payment_status','amount_received',
                  'anodizing_date','anodizing_shift','anodizing_load','anodizing_racked_by','anodizing_bar_number','anodizing_code','anodizing_quantity','anodizing_outside_perimeter','anodizing_length','anodizing_square_feet',
                  'shipping_status','shipping_date','shipping_weight','shipping_due','extrusion_completed','shipping_completed', 'fabrication_completed','anodizing_completed']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['ordered_date'].initial = datetime.today()
        
        self.fields['order_received'].initial = 'Yes'
        self.fields['order_type'].initial = 'RE'
        self.fields['price_method'].initial = 'O'
        self.fields['freight'].initial =  '02'
        self.fields['price_details'].initial =  ''
        self.fields['kit_details'].initial =  ''
        self.fields['quote'].initial =  ''
        self.fields['contract'].initial =  0

        self.fields['warehouse'].initial = '00'
        self.fields['staus_number'].initial = 2
        self.fields['ship_cond'].initial = 0
        self.fields['ship_via'].initial = 'BEST WAY'
        self.fields['F_O_B'].initial = 'SHIP POINT'
        self.fields['COS_project'].initial = 4200100
        self.fields['sales_account'].initial = 3200130

        self.fields['surcharge'].initial = 'No'
        self.fields['A_R_credit'].initial = 'A'
        self.fields['fax_ASN'].initial = 'No'
        self.fields['email_ASN'].initial = 'Yes'
        self.fields['amount_received'].initial = 0
        



    

orders/templates/checkgeneralreport.html
{% extends 'layout.html' %}

{% block title %} Check General Cost {% endblock %}

{% block body %}
                <section>
                    <div class="section-body">
                        <!-- BEGIN DATATABLE 2 -->
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="card">
                                    <div class="card-head style-primary">
                                        <header>Check General Cost</header>
                                        <div class="tools">
                                            <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                                            <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table id="datatable2" style="width: 100%;" class="table order-column hover">
                                                {% load humanize %}
                                                {% for general in general %}
                                                <tr>
                                                    <th>Order ID</th>
                                                    <td>{{ general.id }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Vendor Name</th>
                                                    <td>{{ general.Name }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Transaction Date</th>
                                                    <td>{{ general.Transdate }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Transaction Amount</th>
                                                    <td>{{ general.Transamnt | floatformat:2 | intcomma }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Transaction Quantity</th>
                                                    <td>{{ general.Transqty }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Fiscal Year</th>
                                                    <td>{{ general.Fiscal_Year }}</td>
                                                </tr>
                                                <tr>
                                                    <th>GL Account Number</th>
                                                    <td>{{ general.Accountno }}</td>
                                                </tr>
                                                <tr>
                                                    <th>Type</th>
                                                    <td>{{ general.Type }}</td>
                                                </tr>
                                                {% endfor %}
                                            </table>
                                        </div><!--end .table-responsive -->
                                    </div>   
                                </div>       
                            </div><!--end .col -->
                        </div><!--end .row -->
                        <!-- END DATATABLE 2 -->

                    </div><!--end .section-body -->
                </section>
{% endblock %}

orders/templates/editline.html
{% extends 'layout.html' %}

{% load widget_tweaks %}

{% block title %} Add Lines {% endblock %}

{% block body %}

<section>
	<div class="section-body">
		<div class="row">

			<!-- BEGIN  - FORM -->
			<div class="col-lg-12">
				<div class="card">
					<div class="card-head style-primary">
						<header>Lines Details</header>
						<div class="tools">
							<a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
							<a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
						</div>
					</div>
					<div class="card-body">
						<form class="form" role="form" action="" method="post"> {% csrf_token %}

							<div class="row">
								<div class="row">
									<div class="col-sm-3">
										<div class="form-group floating-label">
											{{ line.order_number| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2"> Sales Order</label>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group floating-label">
											{{ line.cat| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">CAT (how many orders)</label>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group floating-label">
											{{ line.ship_days| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">Shipping Days</label>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group floating-label">
											{{ line.order_total| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">Order Total</label>
										</div>
									</div>
								</div>

								<div class="row">
									<div class="col-sm-2">
										<div class="form-group floating-label">
											{{ line.customer_number| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">Customer Number</label>
										</div>
									</div>
									<div class="col-sm-4">
										<div class="form-group floating-label">
											{{ line.customer_name| add_class:'form-control' | attr:'rows:2'}}
											<label for="textarea2">Customer Name</label>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group floating-label">
											{{ line.travel_days| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">Travel Days</label>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group floating-label">
											{{ line.estimated_costs| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">Estimated Cost</label>
										</div>
									</div>
								</div>
								<hr>															

								<div class="row">
									<div class="col-sm-1">
										<div class="form-group floating-label">
											{{ line.line_number| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">Line</label>
										</div>
									</div>
									<div class="col-sm-2">
										<div class="form-group floating-label">
											{{ line.part_number| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">Part Number</label>
										</div>
										<div class="form-group floating-label">
											{{ line.description| add_class:'form-control' | attr:'rows:2'}}
											<label for="textarea2">Part Description</label>
										</div>
									</div>
									<div class="col-sm-2">
										<div class="form-group floating-label">
											{{ line.whse| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">Warehouse</label>
										</div>
										<div class="form-group floating-label">
											{{ line.alloc| add_class:'form-control' | attr:'rows:2'}}
											<label for="textarea2">Allocation</label>
										</div>
									</div>
									<div class="col-sm-2">
										<div class="form-group floating-label">
											{{ line.qty_order| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">Quantity Ordered</label>
										</div>
										<div class="form-group floating-label">
											{{ line.qty_avail| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">Quantity Available</label>
										</div>
									</div>
									<div class="col-sm-2">
										<div class="form-group">
											{{ line.required_date | add_class:'form-control' | attr:'type:date'}}
											<label for="textarea2">Required Date</label>
										</div>
										<div class="form-group">
											{{ line.promised_date | add_class:'form-control' | attr:'type:date'}}
											<label for="textarea2">Promised Date</label>
										</div>
									</div>
									<div class="col-sm-2">
										<div class="form-group floating-label">
											{{ line.unit_price| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">Unit Price</label>
										</div>
										<p><button>Line Pricing (F6)</button></p>
									</div>
									<div class="col-sm-1">
										<div class="form-group floating-label">
											{{ line.stat| add_class:'form-control'}}
											<label for="select2">Status</label>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-3">
										<div class="form-group floating-label">
											{{ line.ship_tolerance_min| add_class:'form-control'}}
											<label for="regular2">Minimum Shipping Tolerance</label>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group floating-label">
											{{ line.ship_tolerance_max| add_class:'form-control'}}
											<label for="regular2">Maximum Shipping Tolerance</label>
										</div>
									</div>
									<div class="col-sm-2">
									</div>
									<div class="col-sm-2">
										<div class="form-group floating-label">
											{{ line.uos| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">UOS</label>
										</div>
									</div>
									<div class="col-sm-2">
										<div class="form-group floating-label">
											{{ line.price_book| add_class:'form-control' | attr:'rows:2'}}
											<label for="regular2">Price Book (F4)</label>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-12">
										<div class="card-actionbar-row">
											<input type="submit" class="btn btn-flat btn-primary ink-reaction" value="SUBMIT">
										</div>
									</div>
								</div>							
							</div>
						</form>
					</div>
					
				</div>
			</div><!--end .col -->
			<!-- END FORM - TIME ON SITE -->

		</div><!--end .row -->

	</div><!--end .section-body -->
</section>

{% endblock %}

orders/templates/newmaintenance.html
{% extends 'layout.html' %}

{% load widget_tweaks %}

{% block title %} Add Maintenance {% endblock %}

{% block body %}

                <section>
					<div class="section-body">
						<div class="row">

							<!-- BEGIN  - FORM -->
							<div class="col-lg-12">
								<div class="card">
									<div class="card-head style-primary">
										<header>Add Maintenance</header>
										<div class="tools">
											<a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
											<a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
										</div>
									</div>
									<div class="card-body">
										<div class="row">
											<form class="form" role="form" action="" method="post"> {% csrf_token %}	
										
		                                         <div class="row">
													<div class="col-md-12">
															<hr>
															<label class="radio-inline radio-styled col-sm-2">
																<b>Maintenance Date :</b>
															</label>
															<div class="col-sm-4">
															{{ maintenance.date | add_class:'form-control' | attr:'type:date'}}
														</div>
															
													</div>
												
													<!--end .table-responsive -->				
																		
											
													<div class="col-md-12">
															<hr>
															<label class="radio-inline radio-styled col-sm-2">
																<b>Department :</b>
															</label>
															<div class="col-sm-4">

		                                                      {{maintenance.department | add_class:'form-control'}}

															</div>
													</div>
														<div class="col-md-12">
															<hr>
															<label class="radio-inline radio-styled col-sm-2">
																<b>Hours:</b>
															</label>
															<div class="col-sm-4">

		                                                      {{maintenance.hours | add_class:'form-control'}}

															</div>
													</div>
													<div class="col-md-12">
															<hr>
															<label class="radio-inline radio-styled col-sm-2">
																<b>Comment:</b>
															</label>
															<div class="col-md-10">

		                                                      {{maintenance.comment | add_class:'form-control'}}

															</div>
													</div>
												</div>
												<hr>
												<div class="row">
													<div class="col-sm-3">
														<div class="card-actionbar-row">
															<input type="submit" class="btn btn-flat btn-primary ink-reaction" value="SUBMIT">
														</div>
													</div>
												</div>
											</div>
											</form>
										</div>
									</div><!--end .card-body -->
								</div><!--end .card -->
							</div><!--end .col -->
							<!-- END FORM - TIME ON SITE -->

						</div><!--end .row -->
					</div><!--end .section-body -->
				</section>
				<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
				<script type="text/javascript">
					$(document).ready(function(){
						$('#id_shipping_date').attr('required',true)
						$('#id_shipping_weight').attr('required',true)
						$('#id_shipping_status').attr('required',true)
					});
				</script>

{% endblock %}

orders/templates/uploadrevenue.html
<html>
    <head>
        <title>
            Excel file upload and processing
        </title>
    </head>
    <body style="margin-top: 30px;margin-left: 30px;">
        <h3 style="font-style: italic;">Please upload data in .xls or .xlsx sheet</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
                 </p>
        </form>

        <p></p>
        <hr>

       
    </body>
</html>